name: CI

on: [ push, pull_request ]

jobs:
  build:
    name: ${{ matrix.name || 'Build' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - name: Ubuntu
          os: ubuntu-latest
        - name: MacOS
          os: macos-latest
        - name: Windows
          os: windows-latest
      # complete all jobs
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: leanprover/lean-action@v1
